output "domain_identity_arn" {
  description = "The ARN of the domain identity."
  value       = aws_ses_domain_identity.main.arn
}

output "domain_identity_id" {
  description = "The ID of the domain identity."
  value       = aws_ses_domain_identity.main.id
}

output "domain_verification_token" {
  description = "A code which when added to the domain as a TXT record will signal to SES that the owner of the domain has authorised SES to act on their behalf."
  value       = aws_ses_domain_identity.main.verification_token
}

output "dkim_tokens" {
  description = "DKIM tokens generated by SES. These tokens should be used to create CNAME records used to verify SES Easy DKIM."
  value       = var.dkim ? aws_ses_domain_dkim.main.0.dkim_tokens : null
}
